### ISSUE TITLE
Interactive update command

### ISSUE THREAD

**Issue by vyorkin** [purescript/psc-package#128]
It seems that the update process for custom package set is quite tedious (for me at least).
Here is what I usually have to do in order update my custom package set:
1) Run `psc-package updates`
2) Scroll through the output to find packages that need to be updated
2.1. For each package find the corresponding version (open the GitHub page)
3) Make a decision if it needs to be updated and put the next version in packages.json
4) Run `psc-package verify`

Just thinking maybe it'd nice to have something like `psc-package update -i`

**Comment by justinwoo** [comment]
Instead of this being in psc-package, it'd be best to write this as a separate tool. It would be good to remove this update command as it doesn't quite work well in the end either...

I mostly just work with diffs of Dhall code in my own package set (https://github.com/justinwoo/spacchetti) and don't work with the packages.json file directly.

**Comment by gasi** [comment]
FWIW, I found out that `psc-package updates --apply` applies changes to local `.psc-package/<set>/.set/packages.json` file which presumably is not tracked in Git. I found this super confusing as I had to manually copy that `packages.json` to my package set which lives in another repo.

Could you please document what the recommended process is for upgrading dependencies using `psc-package updates`? Thanks 🙇

**Comment by justinwoo** [comment]
That's a question I can't answer either, since I don't know how to correctly use the updates command.

You might ask how it is that I make so many automated changes to packgae-sets every now and then, and the answer is that I have a script to first update Spacchetti (https://github.com/spacchetti/spacchetti/blob/master/scripts/update-from-bower.pl), which then I make a diff to package-sets (https://github.com/spacchetti/spacchetti/blob/master/scripts/diff.pl), and then I mark some packages to be updated by modifying a buffer of the results (https://github.com/spacchetti/spacchetti/blob/master/scripts/copy-changes.pl)

**Comment by gasi** [comment]
To clarify, by _you_ I didn’t mean to single you out @justinwoo, but rather asking the maintainers of `psc-package` in general 😄 

Glad to hear I’m not the only one confused by `psc-package updates`. Other than that, I love this project and that we can move on from Bower — kudos to maintainers!

BTW, sick Perl skills, @justinwoo — you surprise me every day 😜

**Comment by justinwoo** [comment]
Is there something we should do here? This is more related to managing package-sets anyhow, so I don't know if there's a lot we should try to do within Psc-Package and rather defer to more specific solutions, especially considering that it would be fairly useful to use the actual Bower library to do updates on Bower-published packages.

**Comment by vyorkin** [comment]
@justinwoo Do you think it's a good idea to track the "remove the `update` command" or "clarify the `update` command usage" as a separate issue?

**Comment by justinwoo** [comment]
Probably it should at least have an updated message to explain what it's supposed to do more, and be prefixed that it is for package sets e.g. `updates    (package-sets) do whatever in the package set`
