### ISSUE TITLE
Consider if the subcommands `update` and `updates` are too similar

### ISSUE THREAD

**Issue by seagreen** [purescript/psc-package#31]
It's not a big deal, but I think having commands that only differ by `s` might be confusing.

**Comment by paf31** [comment]
Let's rename `updates`. Any ideas for that to rename it to?

**Comment by hdgarrood** [comment]
`check-updates`, `show-updates`, `list-updates`?

**Comment by paf31** [comment]
Any of those sounds good to me 👍

**Comment by wereHamster** [comment]
npm/yarn use `outdated` – Checks for outdated package dependencies (https://yarnpkg.com/en/docs/cli/outdated)

**Comment by alexandradeas** [comment]
As we're on topic, I'm a fan of composable commands, so something like `psc-package list --updates` or `upgradeable` plays well with introducing an easy to use interface where you're remembering conventions rather than individual commands. Following a convention such as `[action] [modifiers]` similar to the interface for `apt-get`
